### ISSUE TITLE
how do i use it

### ISSUE THREAD

**Issue by TetraDT** [Interesting-exe/btd6-unlocker#1]
like when i put the un zipped folder in the mods directory nothing happens where am i supposed to put the folder?

**Comment by Interesting-exe** [comment]
put the dll at https://github.com/Interesting-exe/btd6-unlocker/releases/tag/1.0.0 in the mods folder

**Comment by Interesting-exe** [comment]
idk if the mod works as i havent updated it so good luck i guess

**Comment by Interesting-exe** [comment]
I've updated the mod if you're interested in it
