### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Thebloonpopper202** [Interesting-exe/btd6-unlocker#2]
When I press the key blinds nothing happens.

**Comment by Interesting-exe** [comment]
the mod is probably outdated and i dont really plan on updating it rn

**Comment by TToxo** [comment]
how sad. I have been looking for this mod for a long time.

**Comment by Interesting-exe** [comment]
ok i was bored and ended up updating the mod. make sure you also download [BTD Mod Helper](https://github.com/gurrenm3/BTD-Mod-Helper) and follow its [install guide](https://github.com/gurrenm3/BTD-Mod-Helper/wiki/Install-Guide)

**Comment by TToxo** [comment]
> ok i was bored and ended up updating the mod. make sure you also download [BTD Mod Helper](https://github.com/gurrenm3/BTD-Mod-Helper) and follow its [install guide](https://github.com/gurrenm3/BTD-Mod-Helper/wiki/Install-Guide)

OMG, you have a heart of gold!!
