### ISSUE TITLE
Hello, sorry but... 

### ISSUE THREAD

**Issue by claritybear** [Interesting-exe/btd6-unlocker#3]
Hi, this is not an issue but a request.
Can you create a btd6 mod that allows you to change the money value in a game? (Just like in sandbox mode) 

Thanks!

**Comment by Interesting-exe** [comment]
Sorry I'm not really interested in btd6 right now so i wont make it. You should try asking someone in the [BTD6 Mods & Discussion Discord Server](https://discord.gg/NnD6nRH) if they can make it.

**Comment by claritybear** [comment]
alright my dude
